Remove {ui}size restrictions, replace bad "reverse" checks
kas-gui/easy-cast pull request #6
Opened 2021-03-19 11:41 UTC by dhardy

Closes #5 and #3.

@BartMassey can you review please?

2021-03-19 12:06 UTC, dhardy commented
Also closes #1. Pending review, I'll release v0.2 tomorrow.

2021-03-19 22:41 UTC, BartMassey requested changes
Looks good at a quick read!  It's a lot of code, and I can't say I've read it carefully enough to be 100% confident, but I didn't see anything obviously wrong. Fix a couple of (I think?) wrong Issue references and I think it's good to go.

Thanks much: this turned out to be a ton of work for you. I'm sorry. :slightly_frowning_face:

2021-03-19 22:41 UTC, BartMassey commented on CHANGELOG.md
> +-   Replace bad revert check (#6)
Should be #5 here, I think?

2021-03-19 22:41 UTC, BartMassey commented on CHANGELOG.md
> +-   Fix bad revert checks (#6)
Should be #5 here, I think?

2021-03-20 07:43 UTC, dhardy commented on CHANGELOG.md
> +-   Replace bad revert check (#6)
I usually reference the PR :shrug:

2021-03-20 07:47 UTC, BartMassey approved these changes

2021-03-20 08:34 UTC, merged